import torch

DEVICE = torch.device('cuda:0')
SEED = [649737, 395408, 252356, 343053, 743746]
PROJECT_NAME = "DualStreamPPI_v2"

MULTIMODAL_DATA_DIR = r'/../gz-data/Train/'
TUNING_DATA_PATH = r'/../gz-data/Tune'
VAL_DATA_PATH = r'/../gz-data/Val'

PE_DIM = 16
GAUSSIAN_SIGMA = 4
FOURIER_THRESHOLD = 1.0

FEAT_GNN_HID_DIM = 256
GEO_GNN_HID_DIM = 64
MULTI_GNN_HID_DIM = 64
EDGE_DIM = 1

CONV_AGGR = 'mean'
CONV_DIRECTED = False
CONV_L2_NORM = True

JK_MODE = 'cat'

NUM_LAYER = 2
FUSE_DIM = 64
Dual_FUSE_DIM = 128
OUT_CHANNELS = 1
HEADS = 3
DROPOUT = 0.4

EPOCHS = 100
BATCH_SIZE = 32
LEARNING_RATE = 4e-4
WEIGHT_DECAY = 4e-4
POS_WEIGHT = 1
GRAD_NORM = 0.5
PATIENCE = 8

PRE_MODEL = '/../gz-data/TRAINING_OUTPUT/Saved_model'
TUNING_MODEL = '/../gz-data/TRAINING_OUTPUT/Tuning_model'
PLOT_DIR = '/../gz-data/TRAINING_OUTPUT/plots'

SCHEDULER_T_MAX = EPOCHS
SCHEDULER_ETA_MIN = 1e-6
